GET http://localhost:3000/api/storage/file/tjt4apdje56ws1t3dpwc.jpg-1765390061840-018ff321-f2fd-4385-a4b7-57491a80706b 
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImRmZmY3NmRiLWQzNmMtNDhhMC04ZGJiLTFhYWQyZGI0Y2E4OSIsImlhdCI6MTc2NTM5MDE5NCwiZXhwIjoxNzY1MzkzNzk0fQ.EZDAvZr6jFXSbkIhQDBgxWrNwrQL6UsX60MzfG_FjNQ