GET http://localhost:3000/api/storage/file/info/Taller_3__Ciber_2-1.pdf-1765324503622-f9d4973d-69cb-45bd-bac8-0c38726cb362
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImRmZmY3NmRiLWQzNmMtNDhhMC04ZGJiLTFhYWQyZGI0Y2E4OSIsImlhdCI6MTc2NTM5NDI1NywiZXhwIjoxNzY1Mzk3ODU3fQ.NyaIkRryEYXfo4bRBE2mX0eIaWoMzlvk3nXdlhdiSRc