POST http://localhost:3000/api/account/register/
Content-Type: application/json

{
    "email": "example6@example.com",
    "password": "Password123*",
    "info_account": {
        "first_name": "Jose",
        "last_name": "Garcia",
        "phone": "3123551663"
    }
}

